### ISSUE TITLE
Feedback on Vision document

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/AB-public#104]
Hi all,

Thanks for working on this! I have a few comments and suggestions; I'm happy to do a pull request if that's appropriate.

* "it must increase its respect". I don't think the Web has respect. Or, for that matter, ethical integrity. These are matters for human. What about something like "We will improve Web technology to foster people's trust in the platform."
* Under "Vision for W3C" it says ""The fundamental purpose of the W3C ... provide an open forum." I don't think that's the fundamental purpose of W3C. The fundamental purpose is to work to ensure the long-term health and utility of the Web. I do think that the primary activity of the W3C is to provide an open forum. We also do (or have done) other things like develop software and tools, develop educational materials, and so on.
* After talking about the fundamental purpose (or primary activity) there is a list, but no explanation for it. What about something like "To best carry out this activity:"
* The second bullet uses third person singular, all the other bullets use first person plural.
* Under "Principles and Values": Instead of listing some principles for Web architecture here, could you instead refer to TAG documents (even if you name a few principles like decentralization while doing so)? That would shorten the intro and allow readers to more quickly reach the points about how the organization functions to achieve those architectural goals.
* There some redundancy between the elements of the list under Vision and the elements of the list under principles and values. For example, horizontal review is mentioned in both places. There may be reasons to put them in both places, but the characterization should be more distinct. For example, the vision could be inclusion of all users, regardless of ability (just as one example). And in the second list the characterization would be that we seek to create an accessible environment for collaboration, we conduct accesibility reviews of specifications as part of the standards process, and we develop guidelines to help developers create accessible Web sites.

Lastly, a few years ago we worked with the IETF, ISOC, IAB, and IEEE to create a set of shared principles:
https://open-stand.org/about-us/principles/

I would not expect these principles to be sufficient for a W3C vision document, but they might provide some inspiration, and ideally a W3C Vision document would remain consistent with the Open Stand Principles.

**Comment by michaelchampion** [comment]
(speaking as an observer, not in any official capacity)

Hi Ian, I believe this Draft Note was published more as a placeholder in /TR than as a statement of the current task force consensus. The text in  https://github.com/w3c/AB-public/issues/102#issuecomment-1631649172 has a bit more consensus (I think), partly because it anticipates some of your points about respect, fundamental purpose, and redundancy.  I also believe the AB/TF is coming around to something similar to your point about referring to TAG documents rather than listing web architectural principles ... but perhaps that is just my opinion and not a rough consensus.  You might want to take a look to see which of your suggestions need to be applied to that rough draft.

I'm curious whether you see any specific points in the Open Stand principles that aren't in the draft W3C vision but belong there.  I'm not seeing any myself ...

**Comment by cwilso** [comment]
A better reference to look at for the proposal would be https://github.com/w3c/AB-public/pull/103, specifically https://github.com/w3c/AB-public/blob/2e9e600afbf632a45ea816f31514a07f48ffd760/Vision/proposal.md

**Comment by cwilso** [comment]
@ianbjacobs I think I've addressed these in #111 ; you should take a look, and close this if you agree.  (Or comment you agree, and I'll close when/if that PR is merged.)

**Comment by ianbjacobs** [comment]
@cwilso, thanks for the ongoing work on the document. The changes address nearly all of my comments. I have one remaining suggestion.

I don't love this phrase: "The Web has had a tremendous impact on the world, and will continue to grow its impact.." I can't quite parse the Web "growing its impact." 

I also see that this phrase remains in place: "We believe the World Wide Web should be inclusive and respectful of its users: .." I don't think of the Web as showing respect. People show respect.

This paragraph is the transition from a section on the Web and its challenges, to a series of sections about W3C. I propose to replace the entire paragraph with this:

"In both positive and negative ways, the Web has had a tremendous impact on the world. In the remainder of this document, we describe the vision and operations principles that guide W3C in pursuit of its mission to improve the
Web."

I am proposing "less is more" here. The keywords in this existing paragraph (ethical intent, inclusion, people first, etc.) are discussed elsewhere (in the mission, vision, and ethical principles). I don't know that they need repeating here, and a transition "out of the intro" into the rest of the doc seems useful.

**Comment by TzviyaSiegman** [comment]
@ianbjacobs is this resolved?
