### ISSUE TITLE
Publication of "History"

### ISSUE THREAD

**Issue by frivoal** [w3c/AB-public#105]
With the [upcoming publication](https://github.com/w3c/transitions/issues/560) of the [Vision as a Draft Note](https://github.com/w3c/AB-public/blob/2a60303ab11ed86e1f436ae5e6d3d5ed4ef76584/Vision/Overview.html), the content of https://github.com/w3c/AB-public/blob/main/Vision/History.md will now exist on TR, as an appendix of the first version of the Vision.

How to we want to maintain this History going forward? I can think of 3 ways:
1. Keep the appendix in upcoming publications of the Vision going forward
2. Remove the appendix from subsequent versions of the Vision, and keep an informative link to it in the "Acknowledgements and Supporting Material" section, pointing to the appendix in the dated version where it was included.
3. Publish the History as a separate Note on TR (which almost certainly doesn't need to become a Statement), and informatively link to that from "Acknowledgements and Supporting Material" section
4. Remove the appendix from subsequent versions of the Vision as well as mentions of it in "Acknowledgements and Supporting Material"

My opinion would be:
* **Not 1**, as that takes too much room for secondary material in a document that is attempting to be succinct.
* **Maybe 2**, if the History is considered to be a document that was used as input to early versions of the Vision as it was at that point in time, and worth making easy to discover, but which will not be maintained (just preserved as it was then) and won't be considered current.
* **Maybe 3**, if the History is considered to be a document that is not only input to early versions of the Vision, but  relevant background information to the Vision on an ongoing basis, which we want to be able to maintain (even if we don't necessarily expect to have many changes). 
* **Maybe 4**, if this is considered no longer relevant for ongoing versions of the Vision, merely preserved for historical reasons.

What do people think?

(Note: none of this is particularly troublesome to set up, so I wouldn't worry too much about that aspect).

**Comment by frivoal** [comment]
@dwsinger W3C already publishes a history of the consortium, at https://www.w3.org/about/history/. However, the focus of that document is different from what is covered in https://github.com/w3c/AB-public/blob/main/Vision/History.md

> History is not subject to consensus, one hopes it is fact

The facts are subject to reality, not to consensus. A telling of history is not just the facts, it is a particular narrative and perspectives on those facts, and I am unsure that any telling of history would be equally useful as background for the Vision.

That said, if the Comm Team wants to adopt the particular retelling of history that we have in https://github.com/w3c/AB-public/blob/main/Vision/History.md and put that somewhere on the site, then sure, linking to that would be an option.

**Comment by dwsinger** [comment]
They may refuse or want to massage it, but I think it worth asking them. maybe they'll agree to publish it as a linked separate page, with the Vision content…

**Comment by michaelchampion** [comment]
I lean toward option 2 -- keep an informative link to the History doc in the acknowledgments.  It can live in GitHub not the W3C's site.

IIRC we split it out because several complained about this version of history.  And I vaguely recall an earlier private draft that was even more harsh about XML, WS-*, the RDF stack, etc. than this one. I was *opinionated* not consensus-oriented in my contributions to the early drafts.   There's nothing to be gained from sanitizing it further to get consensus from people who have a more favorable recollection.  And I can't imagine EVER getting consensus on a "hard lessons learned trying to invent a worldwide information space" document until we are all dead :-(

**Comment by michaelchampion** [comment]
> History is not subject to consensus, one hopes it is fact

Indeed. I can't remember how much of the first version of the History I wrote, but here's how I recall our shared purpose:  We were trying to frame 2020 or so as a pivot point in W3C's evolution, and told a story about previous historical epochs. It started with almost a [Cambrian explosion](https://en.wikipedia.org/wiki/Cambrian_explosion) of ideas, only a few of which really got traction.  From roughly 2005 - 2010 (when HTML and DOM split off to WHATWG and XML and web services slid off the crest of the hype cycle) until perhaps the start of the pandemic in 2020, W3C made lots of progress making the more successful innovations truly interoperable, making grudging peace with WHATWG, and generally making the web platform incrementally more powerful, universal, and pervasive. But (ahem, the 2016 US election in particular) crystallized a growing dissatisfaction with the World the Web Wrought characterized by fraud, disinformation, and divisiveness. 

That was all to introduce the Vision of a better web and Guiding Principles W3C could use to drive toward the Vision.  I guess that approach is too apocalyptic (or perhaps too idealistic) for many W3C stakeholders. 🤷 So be it, but it seems useful to acknowledge and point to the original ideas even if the document has evolved in a different direction.

**Comment by frivoal** [comment]
As part of setting up automated builds of the Vision, I've also set up an automated build of History. It can be found here: [https://w3c.github.io/AB-public/History](https://w3c.github.io/AB-public/History)

So, if we want to do option 3, it's easy. We just need to publish that on TR.

If we want to do option 2 or 4, it's also easy, we just need to delete that.

**Comment by fantasai** [comment]
My intention was option 2. If we decide something different later, we can do it later. I'm also OK with 4.

**Comment by chaals** [comment]
> History is not subject to consensus, one hopes it is fact

Unfortunately, as most historians will tell you, that is not really what history is. History is a perspective, hopefully informed by a reasonable interpretation of fact. Histories are absolutely subject to consensus (which they rarely achieve) and also to revision.

My proposal is that we don't try to write a W3C-approved History, and don't publish this.

**Comment by dennis-dingwei** [comment]
Agree Option2. History does not necessarily combine with Vision, better being independent. Maintenance should be considered with reasonable cadence.

**Comment by koalie** [comment]
Considering that is is already published as an appendix of the first version, my preference for future revisions would be 4. I would be ok with 2.

**Comment by cwilso** [comment]
Fixed by https://github.com/w3c/AB-public/pull/132.
