### ISSUE TITLE
Feedback on “different approaches”

### ISSUE THREAD

**Issue by fantasai** [w3c/AB-public#108]
These are my comments from comparing [latest publication](https://www.w3.org/TR/2023/DNOTE-w3c-vision-20230725/) vs [Chris's rewrite](https://github.com/w3c/AB-public/blob/2e9e600afbf632a45ea816f31514a07f48ffd760/Vision/proposal.md) per [VisionTF Agenda](https://www.w3.org/wiki/AB/VisionTF/2023-08-10). See also current state of https://www.w3.org/mission/ which @koalie put together based on the AB text.

First, I want to note that I think the headers in the [published version](https://www.w3.org/TR/2023/DNOTE-w3c-vision-20230725/) would reflect their contents better as:

- Intention
- “Background”, instead of “Introduction”
- Vision for the World Wide Web
- Vision for W3C
- “Goals and Methods” (or somesuch), instead of “Principles and Values”

With that as background, here are my comments:

### Intention ###

I think the [Intention](https://www.w3.org/TR/2023/DNOTE-w3c-vision-20230725/#intention) section should stay. It doesn't need to appear when this text is transcribed into e.g. marketing materials, but it's an important part of this technical report, both framing the text that follows and guiding further development.

### Mission of the W3C ###

Starting up with a mission statement makes sense. However, the one in @koalie's document actually says what we're _doing_ to get to where we want to be, not just what we want out of our activities, and that seems helpful. (Technically “leading the community” is a verb, but it's super vague, could mean anything. E.g. being a social media influencer for an inclusive Web would qualify, but that's really not what we're doing here.)

Compare:
> W3C is leading the Web to its full potential by developing protocols and guidelines that ensure the long-term growth of the Web.

vs

> The W3C leads the community in defining a World Wide Web that is inclusive and respectful of its users, to empower an ethical, equitable, informed, and interconnected society.

See also @ianbjacobs statement in https://github.com/w3c/AB-public/issues/104#issue-1807680123:
> it says "The fundamental purpose of the W3C ... provide an open forum." I don't think that's the fundamental purpose of W3C. The fundamental purpose is to work to ensure the long-term health and utility of the Web. I do think that the primary activity of the W3C is to provide an open forum. We also do (or have done) other things like develop software and tools, develop educational materials, and so on.

And also this other fragment from @koalie's document:
> our vision to make the web work, for everyone

I'm sure there's some way to capture a mission statement that incorporates the key points from the various options above. Rather than replacing the one we have as part of this rewrite, however, maybe we should open a separate issue on that and just keep the one we have as a placeholder until that's hashed out.

### Introduction (Background) ###

* The first two paragraphs of Chris's version are an improvement over the [original](https://www.w3.org/TR/2023/DNOTE-w3c-vision-20230725/#intro). They maintain the important bits of wording, but integrate them together better.
* The last part of this section feels awkward, however:
    * The sentence “The W3C's Technical Architecture Group...is a strong basis to improve the ethical integrity of the Web” really does not feel like it fits here. I would delete it.
    * The previously existing sentences “Technology is not neutral” and “We believe the World Wide Web should be inclusive and respectful”, together with the new sentence “The Web has had a tremendous impact on the world” feel like they belong together in a single paragraph, as they're following a single train of thought. Perhaps in this order?
       > The Web has had a tremendous impact on the world, and will continue to grow its impact in the future, by expanding reach, knowledge, education and services even more broadly. But technology is not neutral; new technologies enable new actions and new possibilities, and we must take responsibility to address the impacts of the Web. We believe the World Wide Web should be inclusive and respectful of its users: a Web that supports truth over falsehood, people over profits, humanity over hate.

### The W3C ###

* The first paragraph in this section is pretty good; I'm not so happy with the next two and trying to articulate why...
* I feel very uncomfortable with the use of “We must” in a vision document, and I kinda want to eliminate it from most places. It's a vision document, not an implementation requirements document: it should describe the world and W3C as we want it to _be_.
* I don't think the last paragraph makes much sense. W3C's impact won't be demonstrated by how it operates, it'll be demonstrated by the results it produces, that's what an impact is...
* Small comment: “around the world and industries work together” should be “around the world and from different organizations and industries” as in the published version, imho that reads better and reflects what we're trying to say better.

### Vision for the World Wide Web ###

I think [this section](https://www.w3.org/TR/2023/DNOTE-w3c-vision-20230725/#vision-web) is hugely impactful, and without it the Vision loses both its sense of purpose and its punch. (You can see how well it works in @koalie's [mission statement](https://www.w3.org/mission/).)

### Operational Principles of the W3C vs Vision for W3C + Principles and Values ###

* I appreciate the attempt to reduce the redundancy and multi-level structure in the original document.
* But the resulting text feels convoluted and less inspiring. :/
* The point about “voluntary global standards” got lost.
* The point about “aim to reduce centralization” got lost.
* The point about “principled, community-wide consensus” got cut down to a side-note on something else.
* The point about “ensuring reliable interoperability” got so specific about methods that it's no longer consistent with the Process...

### Overall Approach to Rewriting ###

I appreciate the approach of taking a stab at rewriting overall, since that can bring up good ideas. I've done it myself in various situations. :) But I think for incorporating the changes, it would be helpful, instead of asking everyone to analyze and try to guess at the rationale for the changes, and deciding all of one vs all of the other on a call, if you could break down the changes into pieces and explain them, and we could discuss them one by one.

At a high level, the changes I see are:
* Add “Mission” seciton at the top.
* Remove the “Intention” section
* Remove the “Vision for the World Wide Web” section.
* Adjust some wording in the first part of the “Introduction” section.
* Revise the last few paragraphs of the “Introduction” section.
* Add a new “The W3C” section.
* Combine “Vision for W3C” and “Principles and Values” into a single section.

The last two changes particularly would benefit from some explanation:
* What is the addition of the new “W3C” section addressing?
* What was the thinking behind the process by which the last two sections were combined? What improvements did you see, that you want us to notice, in the points as a result?

I think there are a lot of good things to discuss here, but I want to break it down. I don't agree with all your changes, and don't want to adopt the rewrite wholesale. But I think we should tackle it piece by piece and get the Vision to a point where it fulfills what you intended here, without regressing what we've accomplished so far.

**Comment by chrisn** [comment]
I think the direction @cwilso was taking with his proposed re-draft is good, but I agree with @fantasai's comments here, both on details of specific sections of the vision, as well as the suggestion to break down the changes as a way to update the /TR draft.

**Comment by cwilso** [comment]
I think I have absorbed most of this feedback and applied it in #111; I'm sure some parts are missing, though.  As this was filed against #103, I think this issue should be closed, though, and comments made in that PR or as individual issues.
