### ISSUE TITLE
Why do you want to change the mission?

### ISSUE THREAD

**Issue by hsano1234** [w3c/AB-public#109]
This is my personal opinion. I suppose I can show my opinion here yet since it looks still unstable what should be the vision document by hearing the meeting today.
Excuse me if it contains some impoliteness.

At first, I have believed the words "Leading the web to its full potential" is the mission of W3C.
Why do you want to change the mission??

I think mission and vision of organization shows what is the organization, what is the organization aiming to. It is underlying faith of participant's mind. It must convince all stakeholders.
Therefore it must be quite abstract words, not be detail descriptions because detail cannot cover entire scope.
I do not think any other words cannot convince many people than ever.

I suppose the answer against "what is the web" or "what is the (full) potential" has huge variants as many as a number of participants in W3C. It is likely 30 years since the web was born. Anyone can no longer re-define "the web" already even by Tim Berners-Lee-san, I suppose.
But it is welcome. Even if everyone has different "the web" in their mind, everyone is aiming to "Leading the web to its full potential". Each different participant may bring different contributions, all of them forms W3C prosperous finally. This is a kind of diversity.

The vision is similar. This is not a proposal though I prefer, for example
"Realizing One Web in the world" or something like.
I feel "One Web" is good words, it may imply a lot interpretation by participants. Each different participant choose different approach nevertheless the vision may lead everyone to one direction.

In another aspect,
vision and mission is like a symbol or slogan. The shorter, the stronger.
English inconvenient people as like as myself may not intend to read text filled up a display. Shorter words is necessary in order to establish in participant's mind.

I think vision and mission is also like a concept on top hierarchy of documents, it does not need many sentences. If detail description or guideline about vision and/or mission is needed, we can write that in ethical web principles, CEPC or another new document following to the vision/mission.
If this "Vision document" means the new document above, we should define solid "vision" and "mission" beforehand.

**Comment by hsano1234** [comment]
Hi Elika-san,
Thank you for your response!

I intend to understand vision and mission is necessary for organization, and intention of the vision TF. But it does not mean always necessary to change mission by changing director-led to member-led entity. I think the words "Leading the web to its full potential" is already independent from Tim-san's original intention under the long history. Actually I heard and considered about the words a lot nevertheless I had very few opportunity to know about Tim-san in my short (2 years) W3C experience.

Mission and vision is a tool to encourage participants. But it implies a risk. When someone feel the mission/vision deviates whose faith, the one may discourage or leave from the organization.
Sony re-defined its "purpose" that is like mission/vision several years ago[1]. Although it is my own understanding, ex-CEO Yoshida-san was struggled very much to make the "purpose" to be inclusive all of Sony employees[2]. Yoshida-san intend to change Sony oriented toward from device manufacturer to service provider, but Sony still has very large number of electronics engineers. The "purpose" have to be forward looking, but must not discourage workers for traditional business.

Now W3C, Inc become also big organization and has very wide application area (not only communication, multimedia but also publication, payment and so on) of course as you know. If you change the mission/vision, the TF is needed determination to understand intentions of overall participants.
As far as I know, Yoshida-san have never talked about "what is creativity" nor "what is technology", if he exhibited examples. He relies on each employee to interpret the words. He probably know the risk of explanation.

Please be careful to describe detail explanation.

[1] https://www.sony.com/en/SonyInfo/CorporateInfo/purpose_and_values/
[2] https://consult.nikkeibp.co.jp/ccl/atcl/20210818_1/
([2] is an article in Japanese. Google translate may help you.)

**Comment by fantasai** [comment]
> But it does not mean always necessary to change mission by changing director-led to member-led entity. 

No, indeed. And I think the intention of this exercise is not to change the mission, but to articulate it more clearly and explicitly. We can also consider if there should be some slight adjustments now that we are considering it... But I think the primary goal of this exercise is to make explicit the existing mission and principles and values of W3C, that until now were only implicit.

So personally, I think our goal here is to do something similar for W3C as Mozilla did in 2007. Mozilla went through an exercise to draft the [Mozilla Manifesto](https://www.mozilla.org/en-US/about/manifesto/details/), see their [original blog post](https://blog.lizardwrangler.com/2007/02/13/introducing-the-mozilla-manifesto/). Mitchell led the effort and the drafting, but she asked the community for input. For many of us contributors, the resulting document was not a new mission, but an expression of the mission we already believed in and were working towards.

I think this is not too different from what you linked about Sony. :) But because Sony is so broad, and W3C is so specific, our final result will take a different form than Sony.

>  ([2] is an article in Japanese. Google translate may help you.)

Thanks. I used https://www.deepl.com/translator and I think it  worked OK. :)

**Comment by hsano1234** [comment]
Thank you Elika-san, 
and thank you Chris-san for picking up in an AB led meeting and explaining intention of the TF/AB.

I do not intend to disturb AB or TF to work for the Vision document.
I wanted only to say, "Mission" "Vision" is not a rule, but is like underlying faith in the stakeholder's mind. I suppose it is also a considerable way to leave a room to rely on stakeholders interpretation. It makes W3C to be more inclusive and extend to unseen area for the future.

I respect your big efforts and hope it will be good light toward bright future.

**Comment by cwilso** [comment]
Sano-san,
I want to say I completely agree with you when you say "vision and mission is like a symbol or slogan. The shorter, the stronger."  I would like to make the Vision much more concise.  I do think it is necessary to light the way to a more principled path for the W3C, and explain more than just "leading the Web to its full potential"; that statement is not wrong, but I'm concerned it does not give enough direction.

Does this resolve your concern, or is there more we should do on this topic?

**Comment by hsano1234** [comment]
Hi Chris-san,
Thank you so much. We can close this topic.
