### ISSUE TITLE
Add to principle around centralization

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#11]
Filed at https://github.com/WebStandardsFuture/Vision/issues/27.

**Comment by mnot** [comment]
In the meantime, I've been discussing this with the IAB, and they seem somewhat keen to adopt it and publish soon:
  https://mnot.github.io/avoiding-internet-centralization/draft-nottingham-avoiding-internet-centralization.html

**Comment by cwilso** [comment]
@mnot I note this was changed with https://github.com/w3c/AB-public/pull/51 to reflect the TAG's current language.  Is this addressed, or does it need further expansion at this point?  (Keeping in mind this is still not the "how will be address this" part.)

**Comment by mnot** [comment]
I think it depends on how detailed the Vision needs to be, as discussed (at great length) elsewhere.

That said, this is a pretty deep topic, and it probably deserves separate treatment.

**Comment by jwrosewell** [comment]
I would prefer to reword the sentence.

> Aim to reduce centralization in web architecture, minimizing single points of failure and single points of control.

to

> Minimize single points of failure and control through the use of decentralized architectures.

**Comment by jwrosewell** [comment]
How about just...

> Minimize single points of failure and control.

**Comment by frivoal** [comment]
@mnot the task force's proposal is to close this generic issue, not to stop the discussion on this topic, but because we felt we were at the point where to make further progress, we'd narrower, more specific issues about the phrasing in place. Is that ok with you?

**Comment by jwrosewell** [comment]
Having reflected on the conversation I understand why the use of the word decentralized is a challenge. Centralized is also challenging for similar reasons. Also there were problems with the use of the word "single". 

Given those issues, and for the next issue, the following text focuses on the three key aspects of decentralization, "innovation",  "freedom", and "all".

"Web architecture which facilitates unrestricted innovation and freedom for all stakeholders"

**Comment by TzviyaSiegman** [comment]
@mnot please see https://www.w3.org/2023/05/25-vision-minutes.html for details

**Comment by mnot** [comment]
Sure, WFM.

(I'm loving the nuanced debate there about how to close this issue :)
