### ISSUE TITLE
Include a Reference to UN Declaration on Human Rights in Vision Doc

### ISSUE THREAD

**Issue by torgo** [w3c/AB-public#115]
We discussed today including the word "rights" in the doc might be a good idea. I pointed out that one of the things we wrote into the [Ethical Web Principles](https://www.w3.org/TR/ethical-web-principles/#intro) was that "We need to put internationally recognized human rights at the core of the web platform" with a reference to the [UN declaration on human rights](https://www.un.org/en/universal-declaration-human-rights/). I'd like to suggest some wording be added to the vision document mirroring that.

**Comment by cwilso** [comment]
I think the proper place for this is the EWP.  I'm not sure we should duplicate that pointer.  Others?

**Comment by dwsinger** [comment]
we discussed this verbally a while back, after, IIRC I suggested formally anchoring the document in the UN declaration, and decided to make this a reference-free piece

**Comment by torgo** [comment]
Ok with this since it looks like the word rights didn't make it in anyway.
