### ISSUE TITLE
"Recognize and embody principles"

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#119]
per @fantasai, this section was deleted, but the "recognize and embody principles" bit might be interesting to keep in there somewhere.

	As W3C leads the Web forward,
	our mission is to recognize and embody fundamental values and principles
	into the architecture of the Web.

**Comment by cwilso** [comment]
I think this is covered well enough by "The Operational Principles for the W3C should reflect the core values of the Web itself."

**Comment by cwilso** [comment]
@fantasai ,  thoughts?

**Comment by fantasai** [comment]
No, the sentence above isn't about our operations. It's about our product: we're embedding our values into the _architecture of the Web_, not just into how we operate. And I think that's a fundamental aspect, and core value, of how we operate. :)

**Comment by cwilso** [comment]
Fixed.
