### ISSUE TITLE
“Vision for W3C” ↔ “Vision for the W3C”

### ISSUE THREAD

**Issue by j9t** [w3c/AB-public#121]
In reference to [_Vision for W3C_](https://www.w3.org/TR/w3c-vision/), when understanding “W3C” as “World Wide Web Consortium” (singular), the title and some other instances of “for W3C” seem to benefit from adding an article (“for the W3C”—“for the World Wide Web Consortium”). The document seems to be clearer and read better that way.

(Curious to learn more if this would be missing something, whether that’s something obvious or rather subtle.)

**Comment by cwilso** [comment]
Sigh.  FWIW, I agree with you.  Unfortunately, both the W3C communications director (@koalie) and the Chicago Manual of Style do not.  :)  (e.g. https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Abbreviations/faq0075.html).  I'm trying to maintain consistency with this, although personally it sounds a bit strange to my ears as well.

**Comment by koalie** [comment]
Thanks @cwilso and sorry @j9t 
You may refer to us as "the World Wide Web Consortium", "the Web Consortium" or "W3C", but not "the W3C" (when using the acronym, please treat it as a proper noun.)
cf. https://www.w3.org/about/press-media/#w3c-brand

**Comment by j9t** [comment]
Interesting. Thanks for clarifying, @cwilso, @koalie!
