### ISSUE TITLE
[Vision] Remove the link to the History

### ISSUE THREAD

**Issue by chaals** [w3c/AB-public#131]
If the vision is built on the view of history described in the link, where does that leave someone like me who does not believe that history is accurate? Am I being co-opted as a claimed supporter of that view by contributing, or should I avoid contributing unless we agree on the history?

Removing the link to the specific view of history promulgated there would help make the process of developing the Vision more inclusive of the W3C community.

Writing an agreed history would meet the same goal, but I doubt that is a feasible project at all. Making the success of the Vision project depend on doing so seems like a long slow path to failure, and I do not recommend it.

**Comment by cwilso** [comment]
Duplicate issue with #105.
