### ISSUE TITLE
Where to define *what* we do

### ISSUE THREAD

**Issue by frivoal** [w3c/AB-public#137]
Section 5 (Vision for W3C) of the vision is about our purpose, why we do what we do, and should capture *what* we do. It starts with:
    
> The World Wide Web Consortium (W3C) was founded as an organization to provide a consistent architecture across the rapid pace of progress in the Web, and to build a common community to support its development. It has become an association where diverse voices from around the world and from different industries and organizations work together to evolve the Web.

Section 6 (Operational Principles for W3C) is about how we go about doing what we do. It starts with:

> The fundamental function of W3C is to provide an open forum where diverse voices from around the world and from different organizations and industries work together to build consensus on voluntary global standards for Web technologies.

While the first one is written as a historical development, and the second one is the core definition of what we do, they're fairly redundant with each other.

Also, that first sentence of section 6 is the only one that defines what we do going forward, and "Operational Principles" is the wrong section for that. It probably fits better in section 5, which tries to defines what we are.

The second sentence of section 5, quoted above, does come kind of close, but it merely states what we have become, without taking a position on whether that is what we ought to be doing, or if it's something we ought to change away from.

**Comment by fantasai** [comment]
We should clean this up before publishing as a non-Draft Note, imho. :)

**Comment by amyvdh** [comment]
One thing which it occurs to me that has been discussed several times but that I am not sure I've seen mention of directly is W3C's status as a 501(c)3 with the responsibility to "[serve a public interest](https://www.irs.gov/pub/irs-pdf/p4221pc.pdf)".  I wonder if we might consider including use of that or a similar phrase in our description.
