### ISSUE TITLE
fine-grained anchors

### ISSUE THREAD

**Issue by frivoal** [w3c/AB-public#139]
Section 6 of the vision has a fairly long list of things, and people are likely to want to refer to specific items in there. It would be convenient if each item in the list had an anchor (and a discoverable one at that), to make hyperlinking convenient.

I'm happy to create a PR for that if that would be helpful, or to let the Editor do it if that's easier.

**Comment by cwilso** [comment]
Happy for you to create a PR, or I'll get to it next week.

**Comment by chaals** [comment]
(Is there a label that covers things like fixing markup/typos/links?)
