### ISSUE TITLE
Increase input and positivity?

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#14]
Originally filed at https://github.com/WebStandardsFuture/Vision/issues/12.

**Comment by cwilso** [comment]
I agree this should be closed at this point.  Subsequent edits have improve the tone, and I believe it is a very balanced introduction at this point.

**Comment by jwrosewell** [comment]
I don't agree that the tone is improved.

However this issue is now being progress under #90 and there's no need to leave this open.
