### ISSUE TITLE
Explicitly en-vision a perfect indefinite future?

### ISSUE THREAD

**Issue by dwsinger** [w3c/AB-public#147]
I wonder if the Vision would benefit from a clear statement of the "perfect indefinite" future, towards which we are always striving, in section 4? Vision statements often have sentences of the form "We see a future in which…" (or "envision" if you like)…

"We envisage a future in which every person who needs the web finds their needs fully met, and they are fully able to engage to meet those needs no matter their language, script, or abilities."

These are kind of "sign-post" statements that I think visions should embody. No, we'll never get there ("needs" are always advancing, for a start). 

Not a strong request, but an idea…

**Comment by cwilso** [comment]
Hmm.  I've let this percolate a bit.  I think we have quite a bit of this perfect indefinite future around the W3C organization itself in the document (): but your statement is about the Web itself.  We've (intentionally) kept the "Vision for the WWWeb" section short, and referential to the EWP; the meat of your statement is covered by those bullet points (Web for all, for the good of its users), but I still see the point you're making about making a "what are we striving for with the Web" statement.

Overall, though, I think it would be a different way of saying what's already there, and not necessarily a clear improvement in how it resonates as a future.

We *do* have this in a small way, but not stated precisely in that manner, in the end of the introduction: "We believe the World Wide Web should be inclusive and respectful of its users: a Web that supports facts over falsehoods, people over profits, humanity over hate."  I think that looks to the future we envision, though it doesn't say it in precisely those words.

Fundamentally, though, we made a choice to make this less about the Web itself, and more about the values and principles behind how we build it; I don't see how to add this without replacing something else.  I am also concerned about adding an unbounded statement that "every person who needs the web finds their needs fully met" - I think there are definite constraints on that (without getting into it too deeply, I'll say: "dark web").

**Comment by fantasai** [comment]
I think this is already covered in https://www.w3.org/TR/w3c-vision/#vision-web

> * The Web is for [all humanity](https://www.w3.org/TR/ethical-web-principles/#allpeople).
> * The Web is designed for the [good of its users](https://www.w3.org/TR/ethical-web-principles/#noharm).
> * The Web must be [safe for its users](https://www.w3.org/TR/ethical-web-principles/#privacy).
> * There is [one interoperable world-wide Web](https://www.w3.org/TR/ethical-web-principles/#oneweb).

It's short, but, I think that's a good thing? It's a pretty compelling vision statement, imho. Is there something critical you think isn't captured there?

**Comment by cwilso** [comment]
AB discussed in meeting April 11 2024 and agreed to close without prejudice.
