### ISSUE TITLE
Recognizing the value provided by the wide diversity of publishers

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#16]
Originally filed at https://github.com/WebStandardsFuture/Vision/issues/2.

**Comment by TzviyaSiegman** [comment]
I believe this has been addressed in the current draft. OK to close?

**Comment by TzviyaSiegman** [comment]
@joshuakoran)

**Comment by TzviyaSiegman** [comment]
agreed to close 10/26/23
