### ISSUE TITLE
Thorough Review should mention technical soundness

### ISSUE THREAD

**Issue by cynthia** [w3c/AB-public#170]
In the items listed in Thorough Review, we mention all of the wide review aspects. I wonder if we should add something around "technically sound" in it.

The core of a TAG design review is around ensuring us not shipping bad technical solutions, and the other aspects don't capture that well (e.g. API soundness, ergonomics, consistency/interoperability with other APIs).

CC: @wareid @torgo @plinss

**Comment by cwilso** [comment]
Resolved by #173 .
