### ISSUE TITLE
W3C's vision should not only be "Vision on Web", but also "Vision for W3C" 

### ISSUE THREAD

**Issue by dennis-dingwei** [w3c/AB-public#25]
W3C’s vision on Web: 
1. One interoperable worldwide web;
2. Accessible and safe for everyone;
3. Good for the humanity; 
4. Implements a unified, extensible web architecture which continues to address the evolving user’s needs.

W3C’s vision for the organization: 
1. Serve W3C’s vision on Web;
2. Be a non-profit standards setting organization sticking to the principles of global, open, fair and transparent;
3. Be an organization centered on human beings favoring accessibility, safe, security and all that matters;
4. Be an organization leading and driving the evolution of web architecture timely addressing the needs of the web community including users, developers, service providers and all other stakeholders.

**Comment by cwilso** [comment]
I'll note this difference was marked in the document already, but should be called out better: the "Our Values for the World-Wide Web" is the vision for the Web, and "Our Action as a Consortium" is the vision for the W3C.

**Comment by cwilso** [comment]
@dennis-dingwei since the merging of #30, I think this is now addressed, and we can close this, but I'd like your take - perhaps I'm missing something.

**Comment by dennis-dingwei** [comment]
Yes thanks
