### ISSUE TITLE
Purpose should encompass public at large

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#3]
Originally filed at https://github.com/WebStandardsFuture/Vision/issues/41.

**Comment by tantek** [comment]
This is an astute insight. The Vision’s Purpose section [https://github.com/w3c/AB-public/tree/main/Vision#our-purpose-focusing-on-the-integrity-of-the-web](https://github.com/w3c/AB-public/tree/main/Vision#our-purpose-focusing-on-the-integrity-of-the-web) can be improved in many ways to more explicitly document W3C’s existing practices which serve the public at large.

Proposed resolutions:
* Add “and public feedback” to the end of the first point “Provide an open forum…”
* Change “Ensure that standards are developed” to “Ensure that standards are openly developed”, perhaps defining “openly developed” in the Glossary per [https://github.com/w3c/AB-public/issues/1](https://github.com/w3c/AB-public/issues/1) which could note that “openly developed” means publicly viewable discussion notes, proposals, issues, drafts, test suites, implementation reports, decisions, and conflict resolutions.
* Add “for the public at large” after “… address evolving use cases”

(Originally published at: https://tantek.com/2022/227/t5/)

**Comment by cwilso** [comment]
This has been resolved.
