### ISSUE TITLE
The Vision no longer has a helpful title

### ISSUE THREAD

**Issue by dwsinger** [w3c/AB-public#35]
The Title used to say what we were going to say, but it's gone. It needs a title, please

A New Vision for the W3C: The integrity of the world-wide-web

or the like

**Comment by cwilso** [comment]
The title is "The Vision".  That wasn't a title - it was a tagline for what we were trying to do with the vision doc, and it was intending to imbue a message.  I stand by dropping it, personally, but if you insist on the one-phrase capture, I think it needs to be better designed.  We shouldn't have taglines that imply things that are not clearly stated elsewhere, and we don't really define "integrity" (the word only occurs once in the document).

As for forensics: this tagline seems to have come from me, in a fairly large rework I did in Feb 2021: https://github.com/WebStandardsFuture/Vision/commit/a1957e060800eb5a559a49af4ec3bd9f888350b3.

**Comment by dwsinger** [comment]
The previous title was the one that was deleted; that was a document title line, and it needs one. I agree it could be better, that using a word that is only implied by the content but not in it is not ideal. 

(I think (but don't care enough to check) that it has a longer history.)

**Comment by dwsinger** [comment]
Actually, the word "integrity" is used to sum up the opening section, so I am not sure that "A New Focus for the W3C: Improving the Web’s Integrity" is using it as an un-anchored word. But it's a kind of wordy title, and could be better, for sure. The document does need a title, though.

**Comment by cwilso** [comment]
See above - I did say it was used one other time in the document.  I remember writing that title, and thinking at the time it was implying a lot of what we were trying to do, but we didn't state that in the document.

If you literally just want "The Vision for the W3C" so we have a bit of text in large font at the top, I'm okay with that.  Is that sufficient?   I'm worried - particularly given the all the other feedback that we need to streamline and make this much, much easier to read (particularly for non-native English speakers) that putting a wordy title that's intended to imply a bunch of stuff will increase the cognitive load and just confuse readers.

**Comment by avneeshsingh** [comment]
+1 to simple title like The Vision for W3C.
If we want a title that captures the essence of the document then we need to really work on it to ensure that it captures the essense in simple text.

**Comment by dwsinger** [comment]
If this document is a vision for the w3c and not (also) a vision for the web, then we need to fork.

Yes, I do think we need a title that captures the essence, the thrust, of the document; as I say, I am not wedded to the old title, but we need something that catches attention and provides a 'hook' into the document. We need to imagine people mentioning, asking, "Have you read 'A vision of web integrity' from the W3C?" (or whatever title we find).

**Comment by cwilso** [comment]
Vision for W3C: Improving the Integrity of the Web
?

**Comment by dwsinger** [comment]
s/for/of the/ and it's a good start (our vision is for the web as a whole as well as the consortium)

"Vision of the W3C: Improving the Integrity of the Web"

or perhaps more succinctly:

"W3C Vision: Improving the Integrity of the Web"

**Comment by avneeshsingh** [comment]
The vision document goes beyond integrity and address the need of embedding ethical values. Integrity is subset of it.
So, I think we need to have a title based on embedding ethical values.

**Comment by dwsinger** [comment]
Having ethical values and adhering to them is a key part, perhaps the principle foundation, of behaving with integrity.

**Comment by cwilso** [comment]
+1 to David's comment above.  I'm concerned about how many terms we use in this document already; we barely mention "integrity", but we don't mention or more importantly define "ethics" at all (except in the reference to the TAG's Ethical Web Principles.)

Avneesh, if you're not opposed I'm inclined to add the headline "W3C Vision: Improving the Integrity of the Web" for now.

**Comment by avneeshsingh** [comment]
The vision is for 10 to 20 years. It includes work on many important topics, one worldwide web, web for everyone, web need to be good for its users, integrity of web and more.

My concern for mentioning only integrity in the heading is that we are giving a wrong indication to external audience that other values are taking back seat. It would be better to emphasize integrity more in the values part, and choose a more neutral heading for the vision document.

**Comment by cwilso** [comment]
@avneeshsingh I think both @dwsinger and I were seeing it the other way around: that "integrity" includes "ethical" as well as more.  That said, I'm not against something different, but I do think if we use the term "ethics" here we need to include it more in the text to give it something to connect to.  (And I'm not sure what exact suggestion you're making in terms of text.)

**Comment by avneeshsingh** [comment]
Ethical values are principles and code of conduct.
Integrity is honesty and conformance to the values.

This document defines two things, vision for the web and vision/mission for W3C.
For the web we envision to embody ethical values in the web.

And how will we (W3C) achieve it?
By focusing on integrity in what we do.

So, the title should address both, what we want for the web and how we intend to achieve it. 

Since you want non-native speakers to provide feedback frankly, I should also mention that integrity without a context can be confused by integrity of content on the web.

**Comment by dwsinger** [comment]
Maybe we need to drop the word integrity, but it is the 'summary word' in the summary paragraph of the first section, so if we do, we should probably revise there.

How about a simpler word like Values? But I am having a hard time phrasing it without pejoratively implying we lost them.

W3C Vision: Emphasis on values

?

**Comment by avneeshsingh** [comment]
emphasis on values is better than focus on integrity.
