### ISSUE TITLE
Oxford commas: yes or no?

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#39]
We just need to be consistent.  Some lists have them, some don't.  Please thumbs up if you believe we should have Oxford commas, thumbs down if you believe we shouldn't, and in a week I'll just implement whichever wins.

**Comment by cwilso** [comment]
For those unaware: the "Oxford comma" is a comma placed between the last and the next-to-last items of a list.  For example, the final comma in "Please bring me a pencil, eraser, and notebook." is an Oxford comma.  Without an Oxford comma, one might write this as "Please bring me a pencil, eraser and notebook."  

Some people prefer Oxford commas, some prefer text without.  They are both grammatically correct in English.  Unfortunately, we currently use both styles in this document (in equal measure, I think), and we should at least be internally consistent.

**Comment by michaelchampion** [comment]
Sigh, you made me read https://en.wikipedia.org/wiki/Serial_comma . 

> What, then, are the arguments for omitting the last comma? Only one is cogent – the saving of space. In the narrow width of a newspaper column this saving counts for more than elsewhere, which is why the omission is so nearly universal in journalism. But here or anywhere one must question whether the advantage outweighs the confusion caused by the omission. 

 As someone educated in "literary" as opposed to "journalistic" American English I'm biased in favor of Oxford commas.  I had always understood the opposition to be about the saving of space / simplification of layout in printed text, which doesn't seem compelling for this document or web content in general.
 
 That said, JUST DECIDE.  I believe the AB Chairs should assert their implicit power as de-facto Benevolent Dictators of AB Document Style; if the chairs don't agree, flip a coin, play rock-paper-scissors, whatever. Whoever can't live with the result should resign in disgrace and meditate on https://en.wikipedia.org/wiki/Law_of_triviality until Enlightenment comes.

**Comment by frivoal** [comment]
I agree with @michaelchampion.

Also https://www.w3.org/Guide/manual-of-style/#Punctuation says:
> Use correct punctuation. A hard copy of The Chicago Manual of Style or The Gregg Reference Manual may be of some help.

The <i>Chicago Manual of Style</i> says:
> In a series consisting of three or more elements, the elements are separated by commas. When a conjunction joins the last two elements in a series, a comma is used before the conjunction

The <i>Gregg Reference Manual</i> says:
> When three or more items are listed in a series, and the last item is preceded by and, or, or nor, place a comma before the conjunction as well as between the other items.

**Comment by avneeshsingh** [comment]
I use commas for improving readability with screen readers because comma simulates a pause of synthetic speech.
For example
The shipment of television sets included black and white and color units. 
A screen reader user understands it better if we write.
The shipment of television sets included black and white, and color units.
This is the practical application for screen reader users.

**Comment by cwilso** [comment]
I'm the sum of all this to be "use Oxford commas everywhere".
