### ISSUE TITLE
This very convoluted sentence... 

### ISSUE THREAD

**Issue by fantasai** [w3c/AB-public#44]
... desperately needs improvement. I can't even tell if it's syntactically valid, I think it's not?

> The fundamental purpose of the W3C is to provide an open forum, where diverse voices from around the world and industries come together, incubate, and build consensus for global standards for Web technologies, including organizations of all sizes (from single-person companies to multi-nationals) and considering public feedback.

Maybe something like this? I'm not sure it's particularly improved but at least it's less of a linguistics puzzle...

> The fundamental purpose of the W3C is to provide an open forum where diverse voices from around the world--including organizations of all sizes (from single-person companies to multi-nationals) and varied industries--come together to incubate and build consensus, with consideration of public feedback, for global standards for Web technologies.

**Comment by cwilso** [comment]
I agree this is a very convoluted sentence that needs attention and simplification.  I don't think the suggestion above does enough to unroll it; it mostly just reorganizes it and trades commas for dashes in a parenthetical (though it does make the "considering public feedback" phrase drop a little better into place.  Definitely worth noodling on some more.

**Comment by michaelchampion** [comment]
FWIW ChatGPT clarifies this as "The main aim of the W3C is to create a platform where people from various backgrounds and organizations, ranging from individual freelancers to large corporations, can work together to agree on and develop international standards for web technologies while taking into account input from the general public." <duck>

**Comment by cwilso** [comment]
Please don't ask ChatGPT to rewrite our documents.

**Comment by michaelchampion** [comment]
Well, it did better than we humans did at writing a coherent sentence;-) And this is a public repo so there aren't confidentiality issues.

I think the appropriate way to use online language tools  is as a "dumb" editorial assistant, not an "intelligent" author or editor.  What does the tool's suggestion miss that is important to the Vision and how can we  write a better version?

The main thing I see:  it misses the key concepts "consensus" and "incubation" by using the vaguer phrase "working together".  And it implies that standards are "developed" after they are  "agreed upon".   And it uses the tech industry term-of-art "platform" in a somewhat confusing way.

Maybe: "The fundamental purpose of W3C is to create a forum where people from various backgrounds and organizations, ranging from individual freelancers to large corporations, can come together to incubate, develop, and ratify international standards for web technologies that serve the interests of the general public."
   
   

-

**Comment by cwilso** [comment]
I should have responded at greater length.  I have no problem with you using ChatGPT personally as an editorial assistant, and IIUC/IANAL/TINLA ChatGPT assigns the rights to the output to you, so it's not a copyright concern.  I DO have a concern with any implication that "oh, we should run this through ChatGPT and have it give us the answer" or that it is a SMART editorial assistant, and its output should be accepted without deep, careful inspection.

I think this sentence needs more work than that.  Among other things, I think it is simply cramming too many concepts into one sentence.

I'm thinking something like:

The fundamental purpose of the W3C is to provide an open forum where diverse voices from around the world work toward consensus for global standards for Web technologies.  This forum includes organizations of all sizes, representatives of industries as well as individuals, and considers public feedback.

**Comment by michaelchampion** [comment]
>  I DO have a concern with any implication that "oh, we should run this through ChatGPT and have it give us the answer" or that it is a SMART editorial assistant, and its output should be accepted without deep, careful inspection.

Completely agree.  In this case, I was struggling to untangle the points being made in the  sentence and wondered "I wonder how ChatGPT would de-convolute it?  ChatGPT uses / is a *language* model so I felt reasonably comfortable asking for its "advice" on a  language question.  I would not use it for substantive questions ... except for programming problems, which are "language" questions too. (In this case, the points it mangled  -- like throwing out the key term "consensus" -- were fairly substantive, but easy to miss because its output seemed clearly written.)

I realize that this is a subtle distinction, so "don't use ChatGPT to rewrite documents" probably a good rule of thumb. But so is "Consider using ChatGPT to explore better ways to write a sentence or paragraph (or express an idea in code), but don't be fooled into thinking it has intelligence or expertise."

Your rewrite looks good, I agree with breaking it up into two sentences.
