### ISSUE TITLE
Community consensus

### ISSUE THREAD

**Issue by mnot** [w3c/AB-public#45]
If 'Vision for the W3C' stays (see #4), it would be good to emphasise that we come to consensus as a whole community, based upon shared principles -- e.g., in a separate bullet point.

I suggest this because we're seeing a concerning trend of folks suggest that WG charters should be treated as contractual -- that once they're given a letter of marque (as it were), they have the right to public a Recommendation, even if implications that go against principles and/or consensus are found after chartering.

**Comment by cwilso** [comment]
Something like "We believe in principled consensus-building as the basis for building standards."  ?

**Comment by mnot** [comment]
Perhaps

> We believe in principled, community-wide consensus-building as the basis for building standards.
