### ISSUE TITLE
Values need further specificity

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#5]
originally filed at https://github.com/WebStandardsFuture/Vision/issues/39.

**Comment by tantek** [comment]
Original issue both has some points and may be requesting more detail than is appropriate for a Vision document.

Per the one response on the original issue, I’m not sure how to adequately address this issue either, except to perhaps consider linking to more detailed documents regarding “good of its users” and “safe for its users”, though I’m not certain enough about that approach to propose resolving in that manner. That is, this issue may merit some additional time and thoughtful consideration to come up with ways to address the points the original issue creator brought up.

Proposed resolution:
* keep this issue open to asynchronous discussion til the end of the year 2022. If it hasn’t made progress by then, consider linking the phrases “good of its users” and “safe for its users” to other related documents at W3C such as the TAG Ethical Web Principles [https://www.w3.org/2001/tag/doc/ethical-web-principles/](https://www.w3.org/2001/tag/doc/ethical-web-principles/)

Alternatively, if the AB deems that consideration (just linking those phrases to the TAG Ethical Web Principles) sufficient now, I would be ok with making edits to the Vision accordingly and closing the issue.

(Originally published at: https://tantek.com/2022/227/t8/)

**Comment by cwilso** [comment]
Sounds good to me.
