### ISSUE TITLE
Thank contributors by name

### ISSUE THREAD

**Issue by chaals** [w3c/AB-public#64]
There are clearly individuals who have contributed to the shape of this document, whether through pull requests or discussions, who are not acknowledged.

Naming people is a friendly gesture and not very hard. Calling them "and the rest of the AB" is not very respectful or gracious.

**Comment by cwilso** [comment]
At the time that text was written, the list of names was actually created exhaustively from those who had contributed to the document - through PRs or participating in discussions.  "And the rest of the AB" was an acknowledgement of the rest of the AB's implicit contribution through supporting the idea of the work; it was certainly not intended to be disrespectful or ingracious, and I don't think anyone took it as such.

How do you think we should identify the names that should be acknowledged?

**Comment by chaals** [comment]
> How do you think we should identify the names that should be acknowledged?

This is always a tricky question. The approach I prefer is to identify anyone who has contributed through PRs or participating in discussions, so I think that's just trying to do that regularly. I know there are plenty of groups that set a higher bar than I would do, and given that we build on so much of what we have learned from others we'll never really get a full list. But I think it's worth a bit of thought, and being clear about how we do it.

**Comment by fantasai** [comment]
https://www.w3.org/2024/09/25-vision-minutes.html#r03
> RESOLUTION: Close 64 with an editorial change to include "and the Vision Task Force"

**Comment by dwsinger** [comment]
I think it may read better and be less likely to ruffle feathers if "notably" were changed to "including", but I leave that idea as purely editorial for the editor to consider

**Comment by tantek** [comment]
Closing with editorial change ([https://github.com/w3c/AB-public/pull/175](https://github.com/w3c/AB-public/pull/175)) merged to include "and the Vision Task Force" per Vision Task Force resolution: [https://www.w3.org/2024/09/25-vision-minutes.html#r03](https://www.w3.org/2024/09/25-vision-minutes.html#r03)

(Originally published at: https://tantek.com/2024/269/t7/)
