### ISSUE TITLE
Adding content related to the future Web

### ISSUE THREAD

**Issue by KotisK** [w3c/AB-public#67]
- Recommend changing the title to "The W3C Vision: Principles and Values". I have added "Principles" due to later use e.g., section "Principles and Values".
- Recommend adding content related to the future Web (since this is a vision document). Specific 'keywords' can reflect W3C work on key technologies for shaping the future Web (in my opinion, it is already here) such as: "Web of Linked data", "Semantic Web", “Web of Everything”. Currently, these terms are missing from the vision document, but in my opinion, this is a large part of W3C efforts and recommendations already (that deserve proper placement in W3C vision).
- Such additions (as proposed above) could be added to the different sections. I provide a few lines below, to get an idea. If I may, I am adding/editing (with bold) a few points in the ‘vision’ and ‘mission’ sections, as follows: 

- Vision for the World-Wide Web
•	The Web is for all humanity.
•	The Web is designed for the good of its users.
•	The Web must be safe **and fair** for its users.
•	There is one **open**, interoperable world-wide Web **for everything (human, machines, things, processes, services, linked data).**

- Vision for the W3C
The W3C is an association where diverse voices from around the world and industries come together to **recommend**, incubate and build consensus for global standards that make up the **future** Web, serving the **Web vision.**
•	We put the needs of users first: above authors, publishers, implementers, paying W3C Members, or theoretical purity.
•	This organization believes in diversity and inclusion of participants from different geographical locations, cultures, languages, accessibility needs, gender identities, and more.
•	We believe in principled, community-wide consensus-building as the basis for building standards.
•	We strongly emphasize fairness, accessibility, internationalization, privacy, and security.
•	Our standards are rooted in a strong royalty-free patent policy and open copyright licenses, openly developed with **the** consensus of industry and key stakeholders.
•	**W3C leads the Web forward, towards the future Web, the semantic Web, the Web of data, the Web of everything (humans, machines, things, processes, services and linked data).**

- Mission of the W3C
The fundamental purpose of the W3C is to provide an open forum **and workspace** where diverse voices from around the world and from different industries work together to build consensus on global standards for **current and future Web** technologies. This forum **and workspace** welcome individuals and organizations of all sizes (from single-person companies to multi-nationals), and takes into active consideration feedback from the general, **technical, and scientific** public.

As the W3C leads the Web forward **(to a future Web, a semantic Web, a Web of data, a Web of everything)**, our mission is to recognize and embody fundamental values and principles into an **open** architecture of the **current and future** Web.

**Comment by michaelchampion** [comment]
> Recommend changing the title to "The W3C Vision: Principles and Values"

👍 Or "Guiding Principles" ?

> Mission of the W3C
The fundamental purpose of the W3C is to provide an open forum and **workspace** ...

👍 to adding "workspace" or even replacing "forum" with that word.  It envisions W3C as a venue to DO things not just TALK.

> W3C work on key technologies for shaping the future Web (in my opinion, it is already here) such as: "Web of Linked data", "Semantic Web", “Web of Everything”. Currently, these terms are missing from the vision document, but in my opinion, this is a large part of W3C efforts and recommendations already 

👎 I envision this document as an honest assessment of the good and bad the Web has done for users/humanity, a Vision of a better web, and a set of Guiding Principles for how to move from what we have to what we need.   Let's not encumber it with mandates to keep doing what W3C has done for almost 30 years now or constraints on which particular technologies must be used to achieve the Vision.

**Comment by KotisK** [comment]
> Regarding W3C mission and vision, I would like just to argue that my point/issue raised was also based on what is already written in W3C mission web page (https://www.w3.org/Consortium/mission) for "...W3C's vision of One Web" and in the Semantic Web web page (https://www.w3.org/standards/semanticweb/) i.e. "The term “Semantic Web” refers to W3C’s vision of the Web of linked data." Thank you!

**Comment by cwilso** [comment]
I would suggest that there are many, many pieces of feedback bound up here, and I'm not sure how to deconstruct them.  It's probably best to file separate issues for unrelated issues - e.g., the suggested title change is one issue, the suggestion of "content related to future web", and the textual suggestions are a LOT of different changes.

I would point out that the phrasing in the current document is the result of a lot of wordsmithing, across a sizable number of people.  That does not mean that changes are a bad thing to suggest - but I think we do need to build consensus on changes (as we did for the text that's there), and not just change wording for the sake of wording.  (e.g.: why is adding "workspace" necessary? How do we define "fair" in this context?)

FWIW, the intent of this vision was to be an organizational vision, not the technical agenda (e.g. Semantic Web); this is similar to the previous mission page, though I think it wandered a bit (I'll note it only referred to the Web ON everything (as in, web runs on multiple devices), and tangentially pointed to web of data as one of those things.  I'm not off-the-cuff convinced that such technical agenda belongs here, but that is perhaps a question to discuss.

**Comment by TzviyaSiegman** [comment]
@KotisK would you be able to break this up into multiple issues to facilitate discussion and pull requests?

**Comment by KotisK** [comment]
I will try to do so, thanks.

**Comment by KotisK** [comment]
I have broke down issue #67 into three new separate issues i.e., #85, #86, and #87. I hope this is what you have requested.
