### ISSUE TITLE
We should start the formatting of the Vision as a (Draft) Note

### ISSUE THREAD

**Issue by dwsinger** [w3c/AB-public#73]
It would be good to get it into the W3C template, as a Draft Note

**Comment by fantasai** [comment]
The AB [has a resolution](https://www.w3.org/2023/03/16-ab-minutes.html#r05) to publish this as a Draft Note, in fact; but it appears this has not yet been done.

> RESOLUTION: remove consensus wording and publish as draft note

@cwilso Can you make this happen?

**Comment by frivoal** [comment]
If that's helpful, I'm happy to share and explain the machinery that builds and publishes the Process in the Process CG. We don't have to do it the same way, but we could.
