### ISSUE TITLE
"Vision for the web" and "Vision for the W3C" might be separate documents?

### ISSUE THREAD

**Issue by dwsinger** [w3c/AB-public#74]
we should consider splitting, as they have different audiences and different uses. But yes, they need to not disagree with each other

**Comment by hober** [comment]
see also #72

**Comment by michaelchampion** [comment]
How should either Vision document be aligned with the TAG Ethical Web Principles? FWIW I think of the EWP as the "vision for the web" and the AB Vision as the "vision for W3C'.  But that view didn't get any support in the initial version of https://github.com/w3c/AB-public/issues/62 beyond some agreement that "sustainability" might be mentioned in the Vision.

**Comment by dwsinger** [comment]
I think our vision for the web should be a condensed document that is consistent with the EWP. We need something short and pithy, and we also need those principles worked out in various ways, the EWP is an important one.

**Comment by michaelchampion** [comment]
> We need something short and pithy

A pithy summary of the key points in the EWP and a pithy commitment to use those principles to guide W3C's work would indeed be a good structure for the Vision document.   So the AB document normatively references the TAG "vision for the web" and elaborates its Vision for the W3C.  But making a separate AB Vision for the Web document that is only loosely consistent with the EWP would create more "attack surface" and bike shedding opportunities than added value.

**Comment by cwilso** [comment]
Resolved by the Task force that these should be kept together; we may add a strategic goals document in the future.
