### ISSUE TITLE
Keep the 2 strategic goals about meeting members business needs and ensuring industry adoption?

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#8]
Originally filed at https://github.com/WebStandardsFuture/Vision/issues/32.

**Comment by cwilso** [comment]
We have woven "cooperation among the participants from different industries" and similar language throughout; I don't believe we SHOULD explicitly say "meet member's business needs" here.

**Comment by chaals** [comment]
I think that part of our vision is that we believe adoption is important as a measure of how what we would like can actually turn into reality. That underpins quite a lot of the discussions we have, and I am not convinced that we have captured it effectively in the current draft.

I request this be reopened as an issue.

**Comment by cwilso** [comment]
An explicit "meet members' business needs" mention is quite different from "ensure that web standards we create gain adoption".  I'm happy to reopen this issue to discussion adoption if you like and change it to focus on adoption, but I think there was clear distaste for implying we are simply there to give Members what they want for their business needs.

If you want to explicitly focus on adoption, though, I'd ask that you propose how to address the role of engine implementers, since much of the "adoption" part needs to flow through those implementations.

**Comment by chaals** [comment]
I'll happily open a new issue when I have had some more thinking time. I agree that "we are here to meet members' business needs" is too simplistic a framing.
