### ISSUE TITLE
Remove reference to the Ethical Web Principles

### ISSUE THREAD

**Issue by jwrosewell** [w3c/AB-public#81]
[Ethical Web Principles](https://www.w3.org/TR/ethical-web-principles) contains guidance which involves a judgement call on behalf of the reader. For example; "[The web should not cause harm to society](https://www.w3.org/TR/ethical-web-principles/#noharm)". Defining "harm to society" is not within the scope of the W3C. 

The Vision document should stand on it's own to avoid confusion.

**Comment by cwilso** [comment]
If we were to remove the reference to building on top of the Ethical Web Principles, I believe we should simply effective subsume nearly that entire document here.  (For example, I do believe that we should build on the principle of "the web should not cause harm to society.")

I would prefer to continue referring to the EWP.

**Comment by jwrosewell** [comment]
>  I believe we should simply effective subsume nearly that entire document here.

That would be a welcome compromise as it would subject the current biased document to wide review and result in refinements. The Ethical Web Principles document would then no longer be required.

In any case retaining the link to the Ethical Web Principles is problematic is it makes the Vision complicated for the reader, and does nothing to address the systemic problems the Vision debate is uncovering. Namely the W3C is either a neutral technical standard body as required under law OR a body lobbying for an ideology. It can't be both.

**Comment by chaals** [comment]
I think your final sentence is irrelevant to this issue.

> the W3C is either a neutral technical standard body as required under law OR a body lobbying for an ideology. It can't be both.

It *can* be neither: for example, a technical standard body that sets certain goals for how the technology it describes will be used in practice.

"Lobbying" as something a Delaware-registered 501.3(c) corporation cannot do has a fairly precise meaning, that doesn't encompass "generally promoting the idea of using a technology that aims to further specific goals".

**Comment by chaals** [comment]
I agree with the thrust of @jwrosewell's comment that it is important to consider the content of the "Ethical Web Principles" document in a broad discussion of our values, rather than simply assuming it has explicitly been endorsed by the W3C community at large, because that assumption is false.

(The TAG was created with the specific ability to propose W3C Recommendations, a long-standing method to produce a statement that can be considered as explicitly endorsed by "the W3C". It chose not to use that process for the EWP, so here we are).

**Comment by cwilso** [comment]
I'm confused by your last statement, @chaals - the TAG can't produce Recommendations.   They can produce Notes, like any group, which are non-binding; they can now ask to elevate a Note to "Statement" status (https://www.w3.org/2023/Process-20230612/#w3c-statement), which involves an AC vote, and I expect they may choose to do so for https://www.w3.org/TR/ethical-web-principles/#sotd - they plan to for the Privacy Principles, I know.

Statements are relatively new - introduced in Process 2021, IIRC.

**Comment by chaals** [comment]
@cwilso See the heading "Architectural Recommendations" in the TAG charter https://www.w3.org/2004/10/27-tag-charter.html and the then-relevant process document. (Oh, Xpointer).

Indeed, the TAG *did* produce a Recommendation once.

**Comment by cwilso** [comment]
Though I see it in the TAG charter, I don't see how the Process (even at the time) enabled that - Recommendations are produced by Working Groups only.  What Recommendation did they produce?

**Comment by chaals** [comment]
http://www.w3.org/TR/2004/REC-webarch-20041215/

**Comment by chaals** [comment]
The Process said "look at the charter to see more about what TAG does". The charter said (among other things - it is worth reading)

> The primary activity of the TAG is to develop Architectural Recommendations. An Architectural Recommendation is one whose primary purpose is to set forth fundamental principles

The precedent is that the TAG did develop a REC-track document following the same steps as any other WG would have.

Subsequently, the TAG stopped proposing Recommendations and instead issued things on its own authority, which as @jwrosewell noted and I agreed is far less than "backed by the rough consensus of the W3C".

**Comment by cwilso** [comment]
Resolved in Vision TF 9/29/2023:  We will continue to refer to the EWP, at least informatively.
