### ISSUE TITLE
Add use cases of "industries"

### ISSUE THREAD

**Issue by igarashi50** [w3c/AB-public#84]
> Implement a unified, extensible, Web architecture, which continues to address evolving use cases for the general public.

I think that we should also add "industries" to the above bullet of principles since Web technologies are used in industries, such as publishing, automotive, broadcasting, IoT, etc. In some cases, they are not connected to the public Internet. The following is my suggested text.

Implement a unified, extensible, Web architecture, which continues to address evolving use cases for the general public and industries.

**Comment by TzviyaSiegman** [comment]
see also #10 and #75

**Comment by cwilso** [comment]
This text no longer exists.
