### ISSUE TITLE
Needs editorial work to reduce redundancy

### ISSUE THREAD

**Issue by cwilso** [w3c/AB-public#9]
Filed at https://github.com/WebStandardsFuture/Vision/issues/29.

**Comment by cwilso** [comment]
Note redundancy and Mike's proposal in linked issue.  This is related to #23 and #25 .

**Comment by cwilso** [comment]
@michaelchampion, thoughts?  I think there's still editorial work needed to reduce redundancy, but it's not effectively captured in this issue anymore.

**Comment by michaelchampion** [comment]
OK with me to close

**Comment by TzviyaSiegman** [comment]
Duplicates #90
