### ISSUE TITLE
For all humanity?

### ISSUE THREAD

**Issue by darobin** [w3c/AB-public#91]
What does it mean that the web is "for all humanity"? I struggle to think of a concrete example in which we would make a decision based on this prescription.

**Comment by chaals** [comment]
Indeed.

**Comment by mnot** [comment]
+1.

**Comment by frivoal** [comment]
To me, that implies for example that a technology which would be inherently inaccessible doesn't belong in what we call the web. Something which is unable to deal with linguistic diversity and other aspects of i18n doesn't belong with the web. Something which is meant for a single country doesn't belong with the web. A technology which would dismiss children as irrelevant to its market doesn't belong in the web. Something which only runs on one platform (which isn't itself universal, and none are) doesn't belong in the web…

Realizing that aspiration is not easy, but the web does, at its core, attempt to have everybody in its target user base.

**Comment by mnot** [comment]
Perhaps we're rehashing old ground here, but the problem with such high-level aspirations is that they require qualification with "To me...".

**Comment by darobin** [comment]
@frivoal I find it problematic that building something "for all humanity" is a list of things _not_ to do. Based on your list if we do nothing then we're successful. Going for the negative also excludes things that may be incrementally good. I don't know if it's still the case, but for the longest time Unicode couldn't deal with the world's full linguistic diversity. PNG as well as audio and video codecs are inherently inaccessible to some people (their inaccessibility has to be compensated for by _other_ technologies).

@TzviyaSiegman I don't think that this is about "picking things apart." I think that having a vision doc should be an improvement over gut-checking that something is right. To me, "for all humanity" just gives licence to whoever is in a position to call the shots to just follow their own gut and claim that it's an ethically-grounded decision.

My recommendation is to instead frame things based on the [capabilities approach](https://en.wikipedia.org/wiki/Capability_approach). This has several advantages:

- It's a developed, thick body of work that provides grounding for debate and change rather than just words.
- It's entirely focused on real well-being improvements and freedoms, pragmatic effects, and actual people rather than abstract ideas like the good of humankind.
- It's meant to produce practical, concrete improvements rather than to describe natural rights. This makes it actually applicable to our work in ways that can realistically be deployed, as opposed to say Human Rights approaches that are meaningful in legal frameworks but that feel (at best) hard to operationalise usefully. For instance, it's trivial to explain the value of accessibility work from a capabilities standpoint, all the way down to every last detail. I'm not even sure how to argue for that based on Human Rights (let alone from "for all humankind").
- It is designed to be measurable (there's a whole body of work dedicated to capabilities evaluation) and extensible (we can come up with new ones for the specifics of our world).
- It ties individual agency with collective decision-making.
- It is a framework that is well-understood by organisations that have a lot of experience in the "doing good things for people" and that understand issues of transnational governance.
- It is directly related to human agency, in ways that have evident bridges to user agents and the priority of constituencies.

I've written some of these points up in [a current draft](https://hackmd.io/m8KtBzr2QtuNju6M5kEOQg) that I'm working on. This ties to #58. I think a definition grounded in user agency also grounds the web in capabilities in a way that provides us with a foundation in ethics, a way to evaluate our work and the current web, and a way to generate ideas for improvements.

**Comment by cwilso** [comment]
To roll back to your original question, "For all humanity" was very direct reference back to https://www.w3.org/TR/ethical-web-principles/#allpeople: The web is for all people.  That seemed like very important groundwork-setting before proceeding to what exactly that meant in terms of practical improvements for all people.

**Comment by TzviyaSiegman** [comment]
We had agreed that we will not be linking out in this document. There are some references at the end. (The link to TAG's believe mention of sustainability will be removed).

**Comment by darobin** [comment]
Ah, apologies if I missed that, I've been out for health reasons and I don't see a resolution to remove links in any of the posted minutes. IMHO, this issue is a great example of why not having links doesn't work. The alternatives are:

1. Copying over from other documents. How do we make sure it's done in a clear and consistent way, and stays up to date? I can see the PR that would bring in @cwilso's fix but this seems suboptimal.
2. Not discussing anything that is more legitimately represented elsewhere. This would seem to remove most of the document, including some of the already short vision section.
3. Asking that the people read the minutes of the TF and AB so that they understand which parts of the document are silently meant to be direct references to things designated by URLs (aka "links").
4. Having a lot of the document be sentences that don't have clear meaning to the people reading them, and hope that works out.

Setting aside questions as to whether the EWP's "for all people" definition is sufficient, if we assume that it's what this document intends to mean here, which of the above strategies should be the preferred one?

**Comment by chaals** [comment]
> We had agreed that we will not be linking out in this document. There are some references at the end. (The link to TAG's believe mention of sustainability will be removed).

For the reasons Robin provided, and because long experience of working with documents suggests that they are really sound, I think this decision wasn't the right one. I had a look for it in issues, but didn't find it - do you have a pointer to the discussion?

**Comment by dwsinger** [comment]
It means that no-one is left out, second-class, or discounted. Not for reasons of accessibility, language, or any of the classes people use to discriminate. We don't do that. The emphatic word here is 'all', not 'humanity' (all as opposed to some, not humanity as opposed to other creatures). Maybe that's not clear?

**Comment by darobin** [comment]
But that still doesn't tell me how I would apply this in practice to make a decision about where the web should go or whether some work item is appropriate, let alone how to prioritise scarce this over that in line with our mission. (I'd expect our vision to be able to help on this.)

When we prioritise work on automotive we aren't working for "all" people, we're just working for people who have cars. And because everything is limited, this is necessarily at the cost of not working to address the problem of some other group. When we prioritise work on colour-blindness, we're not working for "all" people either, only for those who benefit from it. Apart from a limited set of work items that are arguably universal (everyone uses language, needs security, etc.), _most_ of the work we do isn't going to be for all of humankind. And I don't think it's a numbers game: many more people have cars than are colour-blind but I don't think that path leads to the best decision.

It's a fact of the matter that not all people need our work in the same way; some need it more than others. We could make web standards for personal space tourism and it would be "for all humankind" since in theory our specs wouldn't leave anyone out <sup><sub>(should they ever go to space)</sub></sup>.

One reason this opens more cans of worms than it can fish with is because it's aiming at an abstraction rather than at people. Starting from people and thinking about what they _can_ do and who they _can_ be is likely to answer more questions since we can understand the impact on people's agency and devise concrete ways to implement solutions. Some people don't have the the capability to read a lot of the text on the web. Some people don't have the capability to install a web app on their car's dashboard. From an agency perspective we can have informed conversation about which creates more welfare; from an "all of humanity" view I don't see how.

(And since you talk of discounting, the "all of humanity" view can get even more problematic because you have to indicate how you discount future generations. Saying we discount none of them leads straight to Effective Altruism and, well, let's just say that I don't think that's where anyone in this thread wants to go.)

> Maybe that's not clear?

We have seven people in this issue, all of whom are well-acquainted with what the W3C does and what the web ought to do, as well as with the document, including non-public background. Those people either agree that they don't know what this means, or provide definitions that differ from one another. If that's how clear it is to us, I think that we should worry that it might not be clear to others.

**Comment by dwsinger** [comment]
OK, then you want to write the opposite? "We prioritize privileged people who speak the languages we already support, are primarily rich in world terms, and don't need any special adaptation in using the web." If this antithesis is obviously wrong (but plausible) I am not at all sure why the statement itself is objectionable.

There are obvious ways we apply this today:
* user-facing features that cannot easily be adapted to non-Latin-script languages (this used to happen quite often)
* interaction modalities for which we have not thought or provided for people with accessibility needs

so we do have tests for this already. I'm not sure what your problem is with asserting this as a principle we live by.

**Comment by wareid** [comment]
We have to consider the context of the original statement and it's place in the document. If we want to list everything the web is for the document is no longer particularly succinct or effective. 

"The Web is for all Humanity" is maybe a bit lofty, but I don't think anyone here is suggesting that means that every specification must have an application for every person. We must consider the needs of everyone, but as pointed out with something like the Automotive activity, not everyone owns a car or drives. In designing that specification though, we should consider those users, but that doesn't mean find an application for them. 

Perhaps a rewording to "The Web is for everyone" might be a bit more suitable. The Web is here for people when they want to engage with us, we are "for" them, on their side, but only when we're wanted or needed.

**Comment by darobin** [comment]
@wareid I don't disagree that making this less lofty is an improvement, but I think that doesn't get to the heart of the matter. The issue is that this sentence isn't _operative_, it doesn't _do_ anything, it doesn't support action or decision. In a sense there's a show-don't-tell question here. If we're talking about the web as a living project, what does the web _do_ that means it's for everyone? If it's the W3C, what do we _do_ that makes our actions for everyone?

Structurally (but I'm completely sure not at all intentionally) this is an "_[all houses matter](https://pyxis.nymag.com/v1/imgs/7f4/f5d/1ce8699ab95b1483ea5d8aa275694d9a1c-all-houses-matter.w710.jpg)_" statement. I live in a wealthy Jersey suburb, we have no shortage of older people in need of medical attention. If the Doctors Without Borders' mission were that they "believe in health over sickness" and think that health is "for all humanity" then I wouldn't be surprised to see them setting up a tent on my street, there's plenty of work. As things stand, I _would_ be quite surprised to see them showing up here, because DWB "brings medical humanitarian assistance to victims of conflict, natural disasters, epidemics or healthcare exclusion." (An action verb!) Same for the Red Cross: "we help those most in need" and "give priority to the most urgent cases of distress" (More action verbs!)

We need a clear statement of our public-interest mission, a way to explain to the world what we do, potentially to convince people to give us money, and to ground our governance and decisions that cannot be arbitrated on technical merit alone (of which, as you know, there are many). All of these aspects need operative statements. It's not in the public interest that we are for all humanity; it's in the public interest if we do X and Y to bring Z to the greatest number. No one should give us money for believing things or being of the opinion that hate or falsehood are bad; not will that serve to govern us. We have a repeatable process to deliver high-impact improvements (eg. a11y, security) to billions of people. It's what we actually _do_. I could see someone wanting to give money to that, I can also see how keeping such a process is legitimate, just, efficient would provide a foundation for our governance. Etc. etc.

We are not for all humanity. If successful, we do things that empower specific people, ideally those who most need it, to lead lives worth choosing. These are not the same.

**Comment by dwsinger** [comment]
I have a problem with weaker language, and I disagree that it's not operative. It's a principle we _already live by_ and I would be baffled to explain why we would weaken or abandon it.

**Comment by wareid** [comment]
@darobin This framing helps come to an understanding I think, and I wonder if we can borrow somewhat from CEPC here. CEPC is ostensibly a document for *all* members of W3C, however we give priority to the needs and safety of marginalized communities over the majority (and state that several times). 

Thinking about it that way, no one here is saying the web is *not* for everyone, but we believe we need to serve the needs and interests of web users above all, and in particular, users impacted by issues of accessibility, internationalization, security, and privacy. We serve everyone but give priority and attention to the users most impacted by the decisions we make.

I'm not sure how to phrase such a thing succinctly, but I do think we're getting closer to what we really want.

**Comment by dwsinger** [comment]
I seem to recall that this was once covered by explicit calls to work on including poorly-supported languages/scripts, to look at new technologies and how to ensure that they are accessible to all, and so on. Perhaps we need a sentence somewhere that says that these are examples of this principle?

**Comment by cwilso** [comment]
I would point out, @darobin, that the document doesn't say "We are for all humanity."  It says The **Web** is for all humanity."  "We" - the W3C collectively - SHOULD do things that empower specific people, ideally those who most need it, to lead lives worth choosing. The Vision for the W3C section delineates what the **W3C** should focus its energies on, and how it should prioritize: users above authors/implementers/etc, D&I, a11y, sustainability, etc.

These sections were always intended to build on each other.  Indeed, one could simply strip out the "Vision for the World-Wide Web" section and put in a reference to the EWP instead.

To borrow on your DWB example:  I agree, it would be off-mission for DWB to put up a tent on your street, in the same way it would be off-mission for the W3C to focus solely on what browser engines want to implement - because the vision for the W3C is guided by the needs of users first, inclusion, a11y, i18n, privacy, security, etc., not the needs of a few of "all of humanity".  

Think of the "Vision for the WWW" section as if DWB's mission statement had a intro sentence that said "we believe everyone deserves humanitarian medical service", but then proceeded straight to their statement "We offer medical humanitarian assistance to people based solely on need, ... first on the scene when peoples' lives are upended by conflict, disease outbreaks, or natural or human-made disasters."

If it offends you that the vision for the Web itself is there, I will only say
1) I don't believe we truly have a shared vision of what the web is and should be that has been evangelized enough, and I think people tend to define it as whatever they want, so I think it's valuable to put in here.  I think it lays the groundwork for what the Web is, so we can focus in the Vision for the W3C on how the W3C is principled.
2) But if there's a rough consensus that it is in the way, great, I'm not personally attached to it or anything.  The Vision for the World-Wide Web section could be removed wholesale from the document.

**Comment by darobin** [comment]
> I would point out, @darobin, that the document doesn't say "We are for all humanity." It says "The **Web** is for all humanity."

I'm aware, I extended beyond that to exemplify the problem. But staying with the literal quote doesn't address the issue. What does this mean? I can think of two meanings for that statement:

1. The Web, as it exists today, is somehow equally for everyone, doing good things for all people, and all that. Everyone gets a kitten. I think we'd easily agree that that statement is patently false.
2. The Web, as a project, would like to be somehow for everyone, doing good things for all people, etc. Presumably then there's some kind of difference between today's state and that ideal endstate, coupled with some actions to get there.

I think your invented DWB statement is a good comparison here: "we believe everyone deserves humanitarian medical service." It's pretty easy to parse out what that means: everyone should be getting medical attention that promotes their welfare, but that's not the case today. And here's how we make a dent.

That's not what we have here. "We believe everyone deserves the Web." I mean, the web we have I wouldn't necessarily wish on people. There's no obvious here to there. "We bring the web to all, particularly the most vulnerable, through an exacting process requiring accessibility, security, i18n, and privacy." I'm not saying that the right text or even a good sentence, but it's a lot closer to the DWB example you gave.

It doesn't offend me that the vision for the web is there, it bothers me to have unactionable content. One thing I've been doing recently for a piece on how useless tech ethics is has been to read CSR statements from a lot of companies including ones like Exxon or Philip Morris International. One impression that's emerging for me is that those that tell you what they believe in more than what they do are also the ones you wouldn't want to leave your kids unattended with.

If people want to evangelise the web as for the good of all (at PL we say "the web as a public good," which implies changes in how it is managed), but my instinct would be that any effective outreach would also be about problems and solutions rather than goal statements.

I think you make a good point that removing the web definition/vision parts from the document might make it more tractable. It wasn't my initial instinct, but I'm increasingly beginning to think that the needs the Consortium has may be more readily and effectively addressed with something more focused.

**Comment by chaals** [comment]
I note that the text says the Web is for all humanity, but then immediately says that it's for the good of and safe for its users (who aren't all of humanity).

Do we mean to set up this apparent distinction? Perhaps if we were aiming to ensure the benefits and protections accrue to everyone, we wouldn't need to even say the web is "for everyone".

**Comment by cwilso** [comment]
On re-reading this thread, I'm struck by:
1) @darobin said "We bring the web to all, particularly the most vulnerable, through an exacting process requiring accessibility, security, i18n, and privacy." would be a reasonable analog to the discussion we were having.  I think that's the goal of what we're trying to say, so although I agree it's not a great/compelling sentence, if the sentiment isn't getting out, we should figure out why.
2) The TF did examine dropping the "Vision of the Web" section, and agreed not to (https://www.w3.org/2023/08/10-vision-minutes.html#x612).
3) Although we can split the hairs of when we say "for all humanity" and "for its users", I think this is a low-order bit.

**Comment by cwilso** [comment]
AB examined and resolved to close in meeting on April 11 2024.
