### ISSUE TITLE
word consistency about "Web"

### ISSUE THREAD

**Issue by hsano1234** [w3c/AB-public#97]
This is different topic from "What is the Web (or World Wide Web)".

I found several similar words that may describe "Web" e.g. Web, web, World Wide Web or World-Wide Web in the document.
Do they have different meaning?
We should use unique consistent word for same meaning. Otherwise that confuses readers. Word consistency is basic of standardization.
I do not have strong opinion about which is the best word, but recommend to be consistent.

**Comment by frivoal** [comment]
> Do they have different meaning?

No, it is the same.

> We should use unique consistent word for same meaning.

I agree.

I think we can use "Web (or World Wide Web)" in the introduction to be clear that these two words are the same, but after that we should stick to one, with consistent spelling. To avoid making the text too heavy, I think we should simply say "the Web" every time.
